services:
  postgres:
    image: postgres:latest
    container_name: postgres-default-serverless-jest-swagger-prisma
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    # volumes:
    #   - /path/to/local/data:/var/lib/postgresql/data
