// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API Test",
    "version": "1"
  },
  "paths": {
    "/hello": {
      "post": {
        "summary": "Endpoint para dar um HelloWorld",
        "description": "Endpoint responsável por mostrar um hello world",
        "tags": [
          "HelloWorld"
        ],
        "operationId": "hello.post.hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/HelloRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/HelloResponse"
            }
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "Listar todos os produtos",
        "description": "Endpoint responsável por listar todos os produtos sem paginação",
        "tags": [
          "ProductList"
        ],
        "operationId": "listProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ProductsListResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HelloRequest": {
      "properties": {
        "name": {
          "title": "HelloRequest.name",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "HelloRequest",
      "type": "object"
    },
    "HelloResponse": {
      "properties": {
        "message": {
          "title": "HelloResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "HelloResponse",
      "type": "object"
    },
    "ProductsListResponse": {
      "properties": {
        "data": {
          "items": {
            "properties": {
              "id": {
                "title": "ProductsListResponse.data.[].id",
                "type": "number"
              },
              "name": {
                "title": "ProductsListResponse.data.[].name",
                "type": "string"
              }
            },
            "required": [
              "id",
              "name"
            ],
            "additionalProperties": false,
            "title": "ProductsListResponse.data.[]",
            "type": "object"
          },
          "title": "ProductsListResponse.data",
          "type": "array"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductsListResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "http",
    "https"
  ]
};