// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API Test",
    "version": "1"
  },
  "paths": {
    "/hello": {
      "post": {
        "summary": "Endpoint para dar um HelloWorld",
        "description": "Endpoint responsável por mostrar um hello world",
        "tags": [
          "HelloWorld"
        ],
        "operationId": "hello.post.hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/HelloRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/HelloResponse"
            }
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "Listar todos os produtos",
        "description": "Endpoint responsável por listar todos os produtos sem paginação",
        "tags": [
          "Products"
        ],
        "operationId": "listProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ProductsListResponse"
            }
          }
        }
      },
      "post": {
        "summary": "Criar produto",
        "description": "Endpoint responsável por criar produto",
        "tags": [
          "Products"
        ],
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ProductCreateResponse"
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "Listar dados do produto",
        "description": "Endpoint responsável por listar dados do produto",
        "tags": [
          "Products"
        ],
        "operationId": "readOneProduct.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ProductReadOneResponse"
            }
          }
        }
      },
      "delete": {
        "summary": "Remover o produto",
        "description": "Endpoint responsável por remover o produto",
        "tags": [
          "Products"
        ],
        "operationId": "deleteProduct.delete.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Success"
          }
        }
      },
      "put": {
        "summary": "Atualizar produto",
        "description": "Endpoint responsável por atualizar o produto",
        "tags": [
          "Products"
        ],
        "operationId": "updateProduct.put.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductUpdateRequest"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ProductUpdateResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HelloRequest": {
      "properties": {
        "name": {
          "title": "HelloRequest.name",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "HelloRequest",
      "type": "object"
    },
    "HelloResponse": {
      "properties": {
        "message": {
          "title": "HelloResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "HelloResponse",
      "type": "object"
    },
    "ProductsListResponse": {
      "properties": {
        "data": {
          "items": {
            "properties": {
              "id": {
                "title": "ProductsListResponse.data.[].id",
                "type": "number"
              },
              "name": {
                "title": "ProductsListResponse.data.[].name",
                "type": "string"
              },
              "createdAt": {
                "title": "ProductsListResponse.data.[].createdAt",
                "type": "string"
              },
              "updatedAt": {
                "title": "ProductsListResponse.data.[].updatedAt",
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "createdAt",
              "updatedAt"
            ],
            "additionalProperties": false,
            "title": "ProductsListResponse.data.[]",
            "type": "object"
          },
          "title": "ProductsListResponse.data",
          "type": "array"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductsListResponse",
      "type": "object"
    },
    "ProductReadOneResponse": {
      "properties": {
        "data": {
          "properties": {
            "id": {
              "title": "ProductReadOneResponse.data.id",
              "type": "number"
            },
            "name": {
              "title": "ProductReadOneResponse.data.name",
              "type": "string"
            },
            "createdAt": {
              "title": "ProductReadOneResponse.data.createdAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "ProductReadOneResponse.data.updatedAt",
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "title": "ProductReadOneResponse.data",
          "type": "object"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductReadOneResponse",
      "type": "object"
    },
    "ProductCreateRequest": {
      "properties": {
        "name": {
          "title": "ProductCreateRequest.name",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "ProductCreateRequest",
      "type": "object"
    },
    "ProductCreateResponse": {
      "properties": {
        "data": {
          "properties": {
            "id": {
              "title": "ProductCreateResponse.data.id",
              "type": "number"
            },
            "name": {
              "title": "ProductCreateResponse.data.name",
              "type": "string"
            },
            "createdAt": {
              "title": "ProductCreateResponse.data.createdAt",
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "createdAt"
          ],
          "additionalProperties": false,
          "title": "ProductCreateResponse.data",
          "type": "object"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductCreateResponse",
      "type": "object"
    },
    "ProductUpdateRequest": {
      "properties": {
        "name": {
          "title": "ProductUpdateRequest.name",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "ProductUpdateRequest",
      "type": "object"
    },
    "ProductUpdateResponse": {
      "properties": {
        "data": {
          "properties": {
            "id": {
              "title": "ProductUpdateResponse.data.id",
              "type": "number"
            },
            "name": {
              "title": "ProductUpdateResponse.data.name",
              "type": "string"
            },
            "createdAt": {
              "title": "ProductUpdateResponse.data.createdAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "ProductUpdateResponse.data.updatedAt",
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "title": "ProductUpdateResponse.data",
          "type": "object"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductUpdateResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "http",
    "https"
  ]
};